
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class Sbookmenu extends javax.swing.JFrame {

    /**
     * Creates new form Sbookmenu
     */
    public Sbookmenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        searchbook = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        backstock = new javax.swing.JLabel();
        Inputop = new javax.swing.JLabel();
        input = new javax.swing.JLabel();
        sbkmntr = new javax.swing.JButton();
        inputd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        showbook = new javax.swing.JTextArea();
        searchbcombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(45, 52, 54));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        searchbook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbook.setForeground(new java.awt.Color(255, 255, 255));
        searchbook.setText("Search book");

        close1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("x");
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchbook, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel1.setBackground(new java.awt.Color(99, 110, 114));

        backstock.setForeground(new java.awt.Color(255, 255, 255));
        backstock.setText("< back");
        backstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backstockMouseClicked(evt);
            }
        });

        Inputop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Inputop.setForeground(new java.awt.Color(255, 255, 255));
        Inputop.setText("Select input option");

        input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input.setForeground(new java.awt.Color(255, 255, 255));
        input.setText("Input detail");

        sbkmntr.setBackground(new java.awt.Color(9, 132, 227));
        sbkmntr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sbkmntr.setForeground(new java.awt.Color(0, 0, 0));
        sbkmntr.setText("Enter");
        sbkmntr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbkmntrMouseClicked(evt);
            }
        });
        sbkmntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbkmntrActionPerformed(evt);
            }
        });

        inputd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputd.setForeground(new java.awt.Color(0, 0, 0));

        showbook.setColumns(20);
        showbook.setForeground(new java.awt.Color(0, 0, 0));
        showbook.setRows(5);
        jScrollPane1.setViewportView(showbook);

        searchbcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Category", "Price", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backstock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inputop)
                            .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sbkmntr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchbcombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inputop)
                    .addComponent(searchbcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sbkmntr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(backstock, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void backstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backstockMouseClicked
        Home hme= new Home();
        hme.setVisible(true);
        this.setVisible(false);
        hme.setLocationRelativeTo(null);
    }//GEN-LAST:event_backstockMouseClicked

    private void sbkmntrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sbkmntrMouseClicked
        String selectedItem = (String) searchbcombo.getSelectedItem();
        String bookFile = "C:\\Users\\Hafsa\\Documents\\NetBeansProjects\\books.txt";
        String inputdat= inputd.getText().trim();
        try (BufferedReader br = new BufferedReader(new FileReader(bookFile))) {
            String line;
            boolean found = false;
            List<String> books = new ArrayList<>();
            
            while ((line = br.readLine()) != null) {
                books.add(line);
                List<String> matchingBooks = new ArrayList<>();
            
                
                for (String book : books) {
                    String[] bookDetails = book.split(",");

                    String bookID = bookDetails[0].split(": ")[1].trim();
                    String bookName = bookDetails[1].split(": ")[1].trim();
                    String bookCategory = bookDetails[2].split(": ")[1].trim();
                    int bookPrice = 0;
                    int numOfBooks = 0;

                    try {
                        bookPrice = Integer.parseInt(bookDetails[3].split(": ")[1].trim());
                        numOfBooks = Integer.parseInt(bookDetails[4].split(": ")[1].trim());
                    } catch (NumberFormatException ex) {
                        // Handle invalid price or number format
                        showbook.setText("Invalid book details format.");
                        return;
                    }

                    if ((selectedItem.equals("Category") && bookCategory.equalsIgnoreCase(inputdat))
                            || (selectedItem.equals("Price") && String.valueOf(bookPrice).equals(inputdat))
                               || (selectedItem.equals("Name") && bookName.equalsIgnoreCase(inputdat))) {
                        // Book found, update the JTextArea with the book details
                        matchingBooks.add("Book ID: " + bookID + "\n" +
                                "Book Name: " + bookName + "\n" +
                                "Book Category: " + bookCategory + "\n" +
                                "Book Price: " + bookPrice + "\n" +
                                "No of Books: " + numOfBooks);

                        found = true;
                      
                    }
                }
                if (found) {
        // Display all the matching books
        showbook.setText(String.join("\n\n", matchingBooks));
    } else {
                     showbook.setText( "No books found.");
    }

            }      
         br.close();
                    found = true;
                    
                }
            

            
         catch (IOException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_sbkmntrMouseClicked

    private void sbkmntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbkmntrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbkmntrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sbookmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sbookmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sbookmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sbookmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sbookmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inputop;
    private javax.swing.JLabel backstock;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel input;
    private javax.swing.JTextField inputd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton sbkmntr;
    private javax.swing.JComboBox<String> searchbcombo;
    private javax.swing.JLabel searchbook;
    private javax.swing.JTextArea showbook;
    // End of variables declaration//GEN-END:variables
}
